---
- name: Build an image with the docker_image module
  hosts: localhost
  tasks:
    - name: Create a network
      docker_network:
        name: docker_net
  roles:
    - docker-one
    - docker-two

- name: Test connection between docker containers
  hosts: localhost
  tasks:
    - name: Test Connection
      shell: ./test_connection.sh
      register: shell_output
    - debug:
        var: shell_output.stdout_lines
